### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DiegoCatalano** [davidchatting/PatchMatch#1]
Which is license of the PatchMatch ?

Thank you !

**Comment by aglie** [comment]
@DiegoCatalano , if you plan to use it commercially, you should also note that PatchMatch is patented by either Google or Adobe or both.

**Comment by DiegoCatalano** [comment]
Sad, I can't use it commercially, Adobe uses in the Content aware algorithm and google probably uses in the word lens application.
